packages:
  - "packages/*"

catalog:
  typescript: "^5.7.3"
  "@types/node": "^22"
  vitest: "^4.0.18"
  "@eslint/js": "^9.39.2"
  eslint: "^9.39.2"
  prettier: "^3.8.1"
  typescript-eslint: "^8.54.0"
  eslint-config-prettier: "^10.1.8"
  playwright-core: "^1.52.0"
  pid-port: "^2.0.1"
  ps-list: "^9.0.0"
  get-port: "^7.1.0"
  "@modelcontextprotocol/sdk": "^1.26.0"
  zod: "^4.3.6"
  commander: "^14.0.3"
  yaml: "^2.7.1"
