// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (C) 2026 Oleksii PELYKH

import { chmod, lstat, mkdtemp, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import {
  adaptersFor,
  asVariantDetection,
  buildDetectionSource,
  buildPostDetailAnchorProbeSource,
  buildReadinessPredicateSource,
  formatVariantProbes,
  type VariantAdapter,
  type VariantDetection,
  variantNamesFor,
} from "../linkedin/dom-variant.js";
import {
  DOMVariantAmbiguousError,
  DOMVariantUnsupportedError,
  ExtractionTimeoutError,
} from "../services/errors.js";
import { delay } from "../utils/delay.js";
import { jsString } from "../utils/js-string.js";
import type { CDPClient } from "./client.js";

/** The page kind this gate reads; picks the adapter list it binds to. */
const POST_DETAIL_SURFACE = "post-detail" as const;

// ----------------------------------------------------------------------------
// Diagnostic-only selectors ({@link capturePostLoadFailure}).
//
// These no longer feed the readiness predicate.  The predicate is now
// generated from the post-detail adapter registry so it polls the *selected*
// adapter's own anchor; these constants stay because a timeout still wants a
// "which-of-N-is-missing" picture across both dialects' markers, and that
// picture is deliberately wider than any single adapter's binding.
//
// What "wider" means is now exact, and it is what bounds this block (#853).
// The registry's OWN anchors are no longer restated here: the capture reports
// each registered adapter's `ready`, `scopes` and `counts` under that
// adapter's own name, from source generated by
// `buildPostDetailAnchorProbeSource`.  Every constant that survives below is
// one NO adapter anchors on, which is the whole reason a hand-maintained list
// still earns its place — a second copy of a registry anchor would drift, and
// drift silently, reporting a renamed dialect under its old name at the one
// moment the report is being read.  Add a marker here only when it is
// genuinely outside every adapter's binding; anything an adapter owns belongs
// in the registry and arrives through the generator.
// ----------------------------------------------------------------------------

/**
 * `<main>`-scoped author link — anchor pointing to either a member profile
 * (`/in/{slug}`) or a company page (`/company/{slug}`).
 *
 * **Diagnostic-only since the adapter registry landed.**  This was the
 * readiness gate's required first stage, chosen (PR #770) because it survives
 * markup change — which is right for a liveness probe and wrong for a gate
 * guarding variant-specific extraction.  Measured on 2026-08-31 it matched 85
 * elements on a post-detail page where every scraper selector matched 0, so
 * the gate went green on a page the scrapers could not read.  A gate anchor
 * that survives every markup change cannot detect a markup change.
 *
 * It remains useful as a *diagnostic*: paired with
 * {@link POST_AUTHOR_LINK_DOCUMENT_WIDE_SELECTOR} it still separates "page
 * failed to render entirely" from "page rendered but not the post body".
 */
const POST_READY_AUTHOR_LINK_SELECTOR =
  'main a[href*="/in/"], main a[href*="/company/"]';

/**
 * Document-wide author-link selector — diagnostic-only.  Reported alongside
 * {@link POST_READY_AUTHOR_LINK_SELECTOR} so a future regression can
 * distinguish "page failed to render entirely" from "page rendered nav /
 * sidebar chips but not the post body".
 */
const POST_AUTHOR_LINK_DOCUMENT_WIDE_SELECTOR =
  'a[href*="/in/"], a[href*="/company/"]';

// Post-detail interaction markers — aria-label-based markers preferred over
// structural CSS / role selectors.  Each renders only after the post has
// hydrated far enough for downstream extraction.
//
// This rule reached post-detail by citing ADR-007, which is scoped to profile
// and /company/ pages and never claimed this surface; ADR-008 reclaims the
// post-detail citation.  ADR-007 is untouched by that reclamation and still
// governs profile/company readiness — and, per its 2026-09-01 amendment, the
// diagnostic-capture pattern this file also cites it for below.
//
// Diagnostic-only: they no longer satisfy the readiness predicate, which is
// now bound to the selected adapter's own anchor — see ADR-008 § Decision 1
// (a gate anchor that survives every markup change cannot detect a markup
// change).  The probe reports each
// individually so a timeout produces a precise "which-of-N-is-missing"
// signal across both dialects at once.
//
// Hardened 2026-05-07 (lhremote#800): the original `React Like to ` and
// `Comment on` markers verified DEAD across all 4 probed post types in the
// React/SDUI rewrite; only `Text editor for creating` survives at the
// aria-label layer.  Adds `Open reactions menu` — the new aria-label for the
// post-level reactions opener, replacing the direct-Like trigger.
//
// That hardening also added a structural componentkey marker for the SDUI
// post-detail container, which is gone from here since #853: it was
// byte-identical to the SDUI adapter's own first scope, so it was a second
// copy of a registry anchor rather than a marker outside the registry.  The
// capture still probes that exact selector — as a count under `sdui`, beside
// the screen-wrapper fallback the boolean never covered.
const POST_REACT_LIKE_SELECTOR =
  'main button[aria-label^="React Like to "]';
const POST_COMMENT_ON_SELECTOR =
  'main button[aria-label^="Comment on"]';
const POST_EDITOR_SELECTOR =
  'main [role="textbox"][aria-label^="Text editor for creating"]';
const POST_REACTIONS_MENU_SELECTOR =
  'main button[aria-label="Open reactions menu"]';

/**
 * Comment-layer anchor.  Diagnostic-only.
 *
 * Mirrors the selector `SCRAPE_COMMENTS_SCRIPT` and `get-post`'s load-more
 * loop depend on.  Reported as a raw element count rather than a logical
 * comment count — the SDUI markup nests three elements per comment, and
 * de-duplicating them here would hide the shape a stale-selector diagnosis
 * needs.  Zero versus non-zero is the signal.
 *
 * Added for the extraction-failure trigger (#835): when the capture fires
 * because `commentCount` contradicted an empty scrape, `ExtractionFailedError`
 * tells the operator to "repair the selectors for `comments`" — and every
 * other probe in the set answers a readiness question instead.  Without this
 * one the bundle carries no evidence about the layer its own error names.
 */
const POST_COMMENT_ELEMENT_SELECTOR = '[componentkey^="replaceableComment_"]';

/**
 * Legacy `span[dir="ltr"]` selector.  Diagnostic-only.  Reported so a
 * timeout can tell a page serving the pre-SDUI dialect from one serving
 * nothing at all — it matched 82 elements in the 2026-08-31 probe run.
 */
const POST_LTR_SPAN_FALLBACK_SELECTOR = 'span[dir="ltr"]';

// EVERY selector CONSTANT above is interpolated into the emitted probe
// through {@link jsString}, never by hand-quoting as `'${CONST}'`.  The rule
// is quantified over the whole block rather than over a counted list, so it
// neither loosens nor needs restating when a constant is added or removed —
// it WAS written as a count, and #853 falsified the count while leaving the
// rule true, which is how a cardinal mirroring a moving base goes stale in
// silence.  Several of them
// contain double quotes, so the hand-quoted form this replaced happened to
// work; the moment one grows a single quote or a backslash it would emit a
// syntax error or, worse, a valid-but-different selector.  Nothing in the type
// system notices — a hand-quoted site compiles and lints — and the failure
// would be invisible here in particular: the capture's own `.catch` swallows an
// evaluate that throws, so the operator gets no json, no png and no warn line
// at the one moment diagnostics matter.  The one-off selectors written INLINE
// in the probe (`article`, `main`, the `mainFeed` / listitem / menu-button
// anchors) are literals in the emitted program rather than values crossing the
// TS→JS seam, so they are not this rule's subject.

/**
 * Poll the DOM until a LinkedIn post detail page has rendered *in a dialect
 * an adapter can read*.
 *
 * The predicate is generated from the post-detail adapter registry
 * ({@link buildReadinessPredicateSource}) and is satisfied only when exactly
 * one adapter claims the page AND that adapter's own readiness anchor is
 * present.  This is the binding that matters, and it is normative — ADR-008
 * § Decision 1: a readiness gate must anchor on a selector belonging to the
 * same adapter that will perform the extraction, so it cannot go green on a
 * page the extractor cannot read.  The predicate it replaced was
 * deliberately variant-agnostic (chosen for surviving markup change), which
 * is correct for a liveness probe and wrong here — see
 * {@link POST_READY_AUTHOR_LINK_SELECTOR}.
 *
 * **Why zero-match does not raise immediately.**  A page that has not
 * hydrated yet also matches zero adapters, so failing fast on the first
 * probe would be indistinguishable from "LinkedIn changed" and would fire on
 * every slow load.  The loop therefore polls first and classifies once, at
 * the deadline, when "not yet" has been ruled out — which is also the only
 * point at which the distinction is decidable.  Classification then picks
 * the error that matches what was actually observed:
 *
 * | Adapters matching at the deadline | Error |
 * |---|---|
 * | zero | {@link DOMVariantUnsupportedError} — register an adapter |
 * | two or more | {@link DOMVariantAmbiguousError} — tighten the detect anchors |
 * | exactly one | {@link ExtractionTimeoutError} — the dialect is known, it never finished rendering |
 *
 * If the classification probe itself comes back malformed, that is not
 * evidence about the page — only that the probe did not run usefully — so
 * the ordinary timeout is raised rather than blaming LinkedIn for a broken
 * instrument.
 *
 * On timeout, if `LHREMOTE_CAPTURE_DIAGNOSTICS=1`, a best-effort diagnostic
 * capture is written to a per-invocation
 * `${os.tmpdir()}/lhremote-diagnostics-XXXXXX/` directory before the error
 * propagates; see {@link capturePostLoadFailure}.  Opt-in because LinkedIn
 * post-detail pages can include personal data.
 *
 * @param client    - Connected CDP client targeting a LinkedIn page.
 * @param timeoutMs - Polling deadline in milliseconds (default: 15s).
 *
 * @throws {@link DOMVariantUnsupportedError} No adapter claimed the page.
 * @throws {@link DOMVariantAmbiguousError} Two or more adapters claimed it.
 * @throws {@link ExtractionTimeoutError} The selected adapter never became ready.
 */
export async function waitForPostLoad(
  client: CDPClient,
  timeoutMs = 15_000,
): Promise<void> {
  const adapters = adaptersFor(POST_DETAIL_SURFACE);
  const predicate = buildReadinessPredicateSource(adapters);
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    const ready = await client.evaluate<boolean>(predicate);
    if (ready) return;
    await delay(500);
  }

  // Classify what the page actually is before reporting.  One probe, on the
  // failure path only — the happy path pays nothing for it.  The same read
  // feeds both the error's `cause` and the diagnostic bundle below, so the
  // two can never disagree about what was on the page.
  const detection = await probeVariantDetection(client, adapters);

  // capturePostLoadFailure self-gates on LHREMOTE_CAPTURE_DIAGNOSTICS and
  // swallows its own errors, so the error below always propagates unchanged
  // regardless of capture-side outcome.
  await capturePostLoadFailure(client, {
    trigger: "readiness-timeout",
    detection,
  });

  if (detection) {
    if (detection.matched.length === 0) {
      throw new DOMVariantUnsupportedError(
        POST_DETAIL_SURFACE,
        variantNamesFor(POST_DETAIL_SURFACE).map(String),
        { cause: new Error(`detect probes — ${formatVariantProbes(detection)}`) },
      );
    }
    if (detection.matched.length > 1) {
      throw new DOMVariantAmbiguousError(
        POST_DETAIL_SURFACE,
        detection.matched,
        { cause: new Error(`detect probes — ${formatVariantProbes(detection)}`) },
      );
    }
  }

  // Exactly one adapter matched (or classification was unavailable): the
  // dialect is known and it genuinely timed out.
  //
  // The probe counts are deliberately NOT folded into this error. This is the
  // branch where a partially-stale adapter is most likely, so the diagnosis
  // matters most here — but its designed home is the diagnostic capture above
  // (per-registered-adapter detect results, #835), not a `cause` bolted onto
  // an error class this item does not own.
  throw new ExtractionTimeoutError(
    `readiness anchor of the selected ${POST_DETAIL_SURFACE} adapter`,
    timeoutMs,
    "Post-detail",
  );
}

/**
 * Read the per-registered-adapter detect counts for a surface.
 *
 * Centralizes the one discipline every caller of {@link buildDetectionSource}
 * owes: a probe that THROWS is the same kind of non-evidence as one that
 * returns a malformed result, and both must degrade to `null` rather than
 * escaping.  Letting an evaluate error propagate would replace the caller's
 * real failure with an unrelated one AND skip the diagnostic capture — the
 * one artifact that would have explained it.
 *
 * `null` therefore means *the probe did not run usefully*, which is NOT the
 * same claim as "no adapter matched"; callers must fall back to their
 * ordinary failure rather than blaming LinkedIn for a broken instrument.
 *
 * @param client   - Connected CDP client targeting the page in question.
 * @param adapters - The surface's registered adapters.
 * @returns The detection, or `null` when the probe yielded no evidence.
 *
 * @internal Exported for unit testing and for the extraction-failure capture
 *   sites — {@link capturePostDetailExtractionFailure} in this module since
 *   #890, and the reactions-modal and search-results helpers in `operations/`;
 *   not part of the public API.
 */
export async function probeVariantDetection(
  client: CDPClient,
  adapters: readonly VariantAdapter[],
): Promise<VariantDetection | null> {
  try {
    return asVariantDetection(
      await client.evaluate<unknown>(buildDetectionSource(adapters)),
    );
  } catch {
    // Best-effort; the caller's own failure is the real signal.
    return null;
  }
}

/**
 * Cap on the wall-clock time the diagnostic capture is awaited before
 * the caller's timeout is re-thrown.  Without this, a misbehaving CDP
 * connection could prolong error propagation by up to `CDPClient.send`'s
 * own timeout per call (`Runtime.evaluate` + `Page.captureScreenshot`).
 */
const DIAGNOSTIC_CAPTURE_TIMEOUT_MS = 10_000;

/**
 * Mutable cancellation state shared between the outer wrapper and the
 * inner capture body.  The wrapper flips `timedOut` when the bound timer
 * wins the race; the inner body checks between each async step and
 * returns early, giving up any remaining writes so the process can exit
 * promptly.
 */
interface CaptureCancellationState {
  timedOut: boolean;
}

/**
 * Is diagnostic capture switched on?
 *
 * Single definition of the gate, so a caller that wants to skip *preparing*
 * capture inputs asks the same question the capture itself asks rather than
 * re-spelling the comparison.  The capture wrappers keep their own check as
 * well: this is a cost optimisation for callers, never the security boundary.
 *
 * Exact `"1"`, deliberately — `"true"`, `"yes"` and `"0"` are all off.  The
 * artifacts contain LinkedIn page content, i.e. personal data, so the gate
 * opens on one spelling and nothing else.
 *
 * @internal Exported for unit testing and for the capture sites that ask it
 *   before preparing their probe inputs — {@link capturePostDetailExtractionFailure}
 *   in this module, and the reactions-modal and search-results helpers in
 *   `operations/`; not part of the public API.
 */
export function diagnosticCaptureEnabled(): boolean {
  return process.env.LHREMOTE_CAPTURE_DIAGNOSTICS === "1";
}

/**
 * What made a post-detail capture fire.
 *
 * The capture used to have exactly one trigger, so "timeout" could be baked
 * into the filename and the warn line.  Since #835 it also fires when an
 * extraction contradicts itself — a failure that never reaches a deadline —
 * so the trigger travels with the call and names the artifact honestly.  A
 * bundle labelled `timeout` for a sub-second corroboration failure would send
 * the next reader hunting a slow page that was never slow.
 *
 * The vocabulary is deliberately closed rather than a free-form string: these
 * values become filenames operators grep for.
 */
/** @internal Not part of the public API. */
export type PostDetailFailureTrigger =
  | "readiness-timeout"
  | "extraction-failure";

/**
 * Per-trigger artifact stem, warn-line tag, and warn-line wording.
 *
 * The `readiness-timeout` row reproduces the pre-#835 strings exactly — that
 * capture's behaviour is unchanged and its artifact names are already in
 * ADR-007 and in operators' heads.  Only the new trigger gets new words.
 */
const POST_DETAIL_TRIGGER_LABELS: Record<
  PostDetailFailureTrigger,
  { readonly stem: string; readonly tag: string; readonly summary: string }
> = {
  "readiness-timeout": {
    stem: "wait-for-post-load",
    tag: "waitForPostLoad",
    summary: "timeout diagnostics",
  },
  "extraction-failure": {
    stem: "post-detail-extraction-failure",
    // Not `waitForPostLoad`: that gate went green and is not what failed.
    // Tagging this line with it would point the reader at a slow page that
    // was never slow.  Identifier-shaped like the family's other tags
    // (`navigateToProfile`, `waitForReactionsModal`) so a log splitter can
    // still treat the tag as one token.
    tag: "postDetailExtraction",
    summary: "extraction-failure diagnostics",
  },
};

/**
 * What the caller knows about the failure it is capturing.
 *
 * @internal Not part of the public API.
 */
export interface PostDetailCaptureContext {
  /** Which failure fired the capture; names the artifact and the warn line. */
  readonly trigger: PostDetailFailureTrigger;
  /**
   * Per-registered-adapter detect counts, already read by the caller via
   * {@link probeVariantDetection}, recorded verbatim in the bundle.
   *
   * Required rather than optional, and `null`-able rather than omittable: the
   * caller is the only party that knows whether a probe was even attempted,
   * and a bundle silently missing the field would be indistinguishable from
   * one where the probe returned nothing.  `null` records the honest answer —
   * *no usable reading* — which is NOT the claim "no adapter matched".
   */
  readonly detection: VariantDetection | null;
}

/**
 * Best-effort diagnostic capture when reading a post-detail page fails.
 *
 * **Two triggers, not one** ({@link PostDetailFailureTrigger}, #835).  It
 * fires when {@link waitForPostLoad} times out waiting for the DOM anchors,
 * AND when an extraction that got past that gate contradicts itself — a
 * cardinal on the page saying N while the scrape yielded none
 * (`assertCardinalCorroboration`).  The second trigger is why the capture
 * could not stay bound to a deadline: that failure is decided in
 * milliseconds and never reaches one, so a timeout-gated capture left the
 * ADR-007 directive *"inspect these artifacts before changing post-detail
 * selectors"* undischargeable for exactly the defect class it exists to
 * serve.  The trigger travels with the call and names both the artifact and
 * the warn line, so a bundle is never labelled for a timeout that did not
 * happen.
 *
 * Each invocation creates a fresh
 * `${os.tmpdir()}/lhremote-diagnostics-XXXXXX/` directory via
 * `mkdtemp` (atomic; refuses to follow any pre-existing symlink at the
 * prefix) and writes `{trigger-stem}-{timestamp}.json` (trigger, URL,
 * title, DOM probes, per-adapter detect counts, visible text snippet) and
 * a sibling `.png` (full-page
 * `Page.captureScreenshot` with `captureBeyondViewport: true`, when the
 * screenshot succeeds) inside it, so callers can classify the failure —
 * auth wall, DOM change, or silent navigation error.  Per-invocation
 * directories prevent concurrent failures in `get-post` /
 * `get-post-engagers` / `get-post-stats` from clobbering each other's
 * artifacts AND close the TOCTOU window a shared parent directory
 * would otherwise leave open.  The trailing `console.warn` reports
 * only the artifacts that were actually written; the `.png` is
 * best-effort and may be absent.
 *
 * **Opt-in only.** Self-gated on `LHREMOTE_CAPTURE_DIAGNOSTICS=1` —
 * no-op otherwise.  Default-off in production (CLI, MCP server) because
 * the artifacts can contain personal data from the LinkedIn post-detail
 * page.  E2E tests activate it via `vitest.e2e.config.ts` `env` so every
 * run produces diagnostics without touching the codebase.
 *
 * The diagnostics directory is created with mode `0o700` and files with
 * mode `0o600` (POSIX; no-op on Windows) so that personal data in a
 * shared `os.tmpdir()` is not exposed to other local users.
 *
 * The capture is cooperatively cancellable and bounded by
 * {@link DIAGNOSTIC_CAPTURE_TIMEOUT_MS}: the outer wrapper stops awaiting
 * at the cap, and the inner body checks a shared cancellation flag
 * between each step and returns early when it flips — so remaining CDP
 * calls and disk writes are skipped rather than merely un-awaited.  In
 * rare cases the in-flight async step started before the cap may still
 * complete in the background; the process is not held alive by this
 * function beyond the cap plus any such single in-flight step.
 *
 * Any capture-side failure is swallowed so the caller's original error
 * always propagates unchanged.
 *
 * Probe set: `{ trigger, href, title, hasMain, hasMainFeed,
 * mainFeedListItemCount, mainFeedListItemsWithMenuButton,
 * mainFeedListItemsViableForPostScrape, hasAuthorLink,
 * hasAuthorLinkInMain, hasLtrSpans, hasArticles, hasReactLikeButton,
 * hasCommentOnButton, hasTopLevelEditor, hasReactionsMenu,
 * commentElementCount, bodyTextSnippet, variantAnchors,
 * variantDetection }` —
 * the fixed-selector probes mirror the container-selection logic in
 * `SCRAPE_POST_DETAIL_SCRIPT`: it scopes from `<main>` (fallback) →
 * `[data-testid="mainFeed"]` → `div[role="listitem"]` inside that
 * feed → per-item `button[aria-label^="Open control menu for post"]`
 * → items with `offsetHeight >= 100` (the scraper skips smaller
 * skeleton/hidden items).  Each layer is probed separately so a
 * future timeout reproduces the exact selector-presence picture
 * without re-running the wait.  Counts (rather than booleans) for
 * the listitem, menu-button, and viable-item layers help Phase 2
 * distinguish "wrapper renamed" from "no items rendered yet" from
 * "items present but skeleton-sized" — a healthy `mainFeed` with
 * zero listitems is a different failure mode than a missing
 * `mainFeed`, and items with menu buttons but `offsetHeight < 100`
 * would be picked up by a naive count yet rejected by the scraper.
 * The menu-button count is scoped to listitems inside `mainFeed`
 * (not document-wide) so it can't be inflated by unrelated buttons
 * elsewhere on the page.
 *
 * The post-#771 probes (`hasAuthorLinkInMain`, `hasReactLikeButton`,
 * `hasCommentOnButton`, `hasTopLevelEditor`) pin exactly which
 * post-anchored signal is missing.  They no longer shadow
 * {@link waitForPostLoad}'s readiness predicate — that is now bound to the
 * selected adapter — and the divergence is deliberate: the per-adapter
 * detect counts say *which dialect*, while these say *how far the page
 * got*, and a timeout wants both.
 *
 * The lhremote#800 hardening probe `hasReactionsMenu` covers the
 * `Open reactions menu` aria-label that replaced the dead
 * `React Like to ` trigger.  A future timeout that fires after
 * `hasReactLikeButton` and `hasCommentOnButton` go dead but before
 * `hasReactionsMenu` arrives will pin the regression to the SDUI
 * marker layer specifically.  That hardening's other probe was a
 * boolean over the SDUI post-detail container, and #853 replaced it
 * with `variantAnchors` rather than dropping it: the same selector is
 * still read, as a COUNT under the dialect that owns it and beside the
 * screen-wrapper fallback a container-only boolean never covered.
 *
 * `variantAnchors` is that replacement, and it is a WIDENING of this set
 * rather than a substitution within it.  It reports, per REGISTERED
 * post-detail adapter and keyed by that adapter's own `variant`, the
 * match counts for its `ready` anchor, each of its `scopes` candidates
 * and each of its `counts` candidates — four anchors that went entirely
 * unprobed before it, including both of the legacy dialect's.  The
 * source is generated by `buildPostDetailAnchorProbeSource` from the
 * registry itself, so a dialect renamed there cannot keep being reported
 * under its old name here, and registering a third adapter needs no edit
 * in this file.  `detect` is deliberately absent: it is read once on the
 * classification path and reaches the bundle as `variantDetection`, so
 * giving it a second home here would report one anchor ROLE twice.  That is
 * about the role, not about the selector: a dialect may use one string in two
 * roles, and `legacy` does — its `detect` IS its `scopes[0]`, so that selector
 * is genuinely read twice, once per probe, and the two counts can differ
 * because the reads are seconds apart on a page that is still hydrating.  Read
 * such a disagreement as evidence about the PAGE, never as a defect in either
 * probe; ADR-007 § 2026-09-04 Amendment (#853) records why removing the
 * duplicate would cost more than keeping it.  Read the two fields together — `variantDetection` says
 * WHICH dialect the page is, `variantAnchors` says how far that dialect's
 * own anchors got, and the fixed probes above say how far the page got in
 * markers no dialect owns.
 *
 * `variantDetection` is the field the fixed probes above structurally
 * cannot supply, and the reason #835 exists: every probe in that set is a
 * hard-coded selector, so a page serving a dialect nobody registered looks
 * exactly like one whose registered adapter matched but whose field
 * selectors went stale.  Read it together with `matched`, which is what
 * decides between the three cases `buildDetectionSource` distinguishes:
 * nothing matched (all probes 0 — register an adapter), two or more matched
 * (a hybrid page — tighten the detect anchors), exactly one matched (the
 * dialect is known, so repair that field's selectors).  `null` records that
 * the probe yielded no usable reading, which is NOT the claim "no adapter
 * matched".
 *
 * Mirrors the diagnostic-capture pattern documented in ADR-007 for
 * `navigateToProfile` — same env var, same artifact structure, same
 * cancellation discipline.  This citation is deliberately NOT reclaimed by
 * ADR-008: ADR-007 § 2026-05-05 Amendment names this function by name, so it
 * is the pattern's own home rather than a post-detail borrowing.
 *
 * @param client  - Connected CDP client targeting the failed page.
 * @param context - Which failure fired the capture, plus the caller's
 *   already-read {@link probeVariantDetection} result.
 *
 * @internal Exported for unit testing; not part of the public API.  It was
 *   additionally exported for the operation-layer extraction-failure sites
 *   until #890 moved the helper that composed it into this module, so
 *   {@link capturePostDetailExtractionFailure} is now its only caller outside
 *   {@link waitForPostLoad}.
 */
export async function capturePostLoadFailure(
  client: CDPClient,
  context: PostDetailCaptureContext,
): Promise<void> {
  if (!diagnosticCaptureEnabled()) return;
  const state: CaptureCancellationState = { timedOut: false };
  let bound: NodeJS.Timeout | undefined;
  try {
    await Promise.race([
      // Attach a no-op catch to the inner promise so a late rejection
      // (after the timer wins the race) does not escape as an
      // UnhandledPromiseRejection — capture-side errors must always be
      // swallowed to keep the caller's failure propagating unchanged.
      capturePostLoadFailureInner(client, context, state).catch(
        () => undefined,
      ),
      new Promise<void>((resolve) => {
        bound = setTimeout(() => {
          state.timedOut = true;
          resolve();
        }, DIAGNOSTIC_CAPTURE_TIMEOUT_MS);
      }),
    ]);
  } catch {
    // Capture itself failed; do not mask the caller's error.
  } finally {
    if (bound !== undefined) clearTimeout(bound);
  }
}

/**
 * Write an extraction-failure diagnostic bundle for the post-detail page the
 * client is sitting on, then return so the caller can re-throw (#835, #890).
 *
 * Every call site raises a **deadline-free** failure: {@link waitForPostLoad}
 * went green, and only then did the page turn out to be unreadable.  A capture
 * bound to a deadline could never see any of them, which is what left ADR-007's
 * "inspect these artifacts before changing post-detail selectors" directive
 * undischargeable for exactly this defect class.
 *
 * Shared rather than restated per operation (#890).  `getPost` and
 * `getPostStats` fail at the *same two outcomes* of the *same generated
 * script* on the *same surface*, so a per-operation copy would be identical
 * line for line — and `dom-variant.ts` is explicit throughout that
 * hand-maintained copies of a rule drift apart.  Its siblings in `operations/`
 * stay local because theirs are not copies: `captureEngagerExtractionFailure`
 * and `captureSearchResultsExtractionFailure` bind different surfaces, hence
 * different adapter lists and different capture functions.  This one is the
 * only case where two callers would have written the same body.
 *
 * The detect probe is skipped when capture is off.  It is a diagnostic-only
 * read whose sole consumer is the bundle, so running it on a default-off CLI
 * or MCP run would spend a `Runtime.evaluate` in the page for nobody — and
 * {@link capturePostLoadFailure}'s own gate fires too late to prevent that,
 * because the probe would already have been evaluated as its argument.  Asking
 * {@link diagnosticCaptureEnabled} rather than re-spelling the comparison
 * keeps one definition of the gate; the capture still re-checks it, so this
 * is a cost optimisation and never the boundary itself.
 *
 * Never throws: {@link probeVariantDetection} degrades to `null` and
 * {@link capturePostLoadFailure} swallows its own failures, so the caller's
 * error always propagates unchanged.
 *
 * @param client - Connected CDP client still sitting on the failed page.
 *
 * @internal Exported for the operation-layer extraction-failure sites; not
 *   part of the public API.
 */
export async function capturePostDetailExtractionFailure(
  client: CDPClient,
): Promise<void> {
  if (!diagnosticCaptureEnabled()) return;
  // Per-registered-adapter detect counts, read alongside `matched`: together
  // they separate "LinkedIn served a dialect nobody registered" (nothing
  // matched) from "a hybrid page needing tighter detect anchors" (two or more
  // matched) from "our adapter matched, so this field's selectors went stale"
  // (exactly one).  Nothing else in the bundle can make those distinctions —
  // every other probe is a fixed selector.
  const detection = await probeVariantDetection(
    client,
    adaptersFor(POST_DETAIL_SURFACE),
  );
  await capturePostLoadFailure(client, {
    trigger: "extraction-failure",
    detection,
  });
}

/**
 * The per-adapter anchor probe, generated once from the surface's registry.
 *
 * At module load rather than per capture: the adapters cannot change between
 * calls, and generating inside the failure path would put string-building on
 * the one code path that runs when something has already gone wrong.
 */
const POST_DETAIL_ANCHOR_PROBE_SCRIPT = buildPostDetailAnchorProbeSource(
  adaptersFor(POST_DETAIL_SURFACE),
);

/** One registered dialect's anchor reading, keyed by the adapter's `variant`. */
interface PostDetailAnchorReading {
  /** Matches for that adapter's own readiness anchor. */
  ready: number;
  /** Matches per extraction-root candidate, keyed by the selector itself. */
  scopes: Record<string, number>;
  /** Matches per engagement-counts candidate, keyed by the selector itself. */
  counts: Record<string, number>;
}

/** What {@link POST_DETAIL_CAPTURE_PROBE_SCRIPT} evaluates to in the page. */
interface PostDetailCaptureProbe {
  href: string;
  title: string;
  hasMain: boolean;
  hasMainFeed: boolean;
  mainFeedListItemCount: number;
  mainFeedListItemsWithMenuButton: number;
  mainFeedListItemsViableForPostScrape: number;
  hasAuthorLink: boolean;
  hasAuthorLinkInMain: boolean;
  hasLtrSpans: boolean;
  hasArticles: boolean;
  hasReactLikeButton: boolean;
  hasCommentOnButton: boolean;
  hasTopLevelEditor: boolean;
  hasReactionsMenu: boolean;
  commentElementCount: number;
  bodyTextSnippet: string;
  variantAnchors: Record<string, PostDetailAnchorReading>;
}

/**
 * The whole in-page probe expression, composed once at module load.
 *
 * A named constant rather than a template literal inlined at the evaluate, and
 * the reason is that a hand-written wrapper splicing a generated program into
 * itself is the one part of this capture nothing else can grade.  A syntax
 * error here — a hand-quoted selector, a stray backtick inside one of the
 * comments below, a generated key colliding with a fixed one — makes
 * `client.evaluate` reject; {@link capturePostLoadFailure}'s own `.catch`
 * swallows that; and the operator gets no json, no png and no warn line at the
 * one moment they are reading diagnostics.  Naming it lets the Tier-2 oracle
 * evaluate THIS string in a real browser rather than a lookalike it rebuilt,
 * which is the only way that failure is ever observed before a field report.
 *
 * @internal Exported for testing; not part of the public API.
 */
export const POST_DETAIL_CAPTURE_PROBE_SCRIPT = `(() => {
    ${POST_DETAIL_ANCHOR_PROBE_SCRIPT}
    const mainFeed = document.querySelector('[data-testid="mainFeed"]');
    const listItems = mainFeed
      ? Array.prototype.slice.call(mainFeed.querySelectorAll('div[role="listitem"]'))
      : [];
    const itemsWithMenu = listItems.filter(function (item) {
      return item.querySelector('button[aria-label^="Open control menu for post"]') !== null;
    });
    // SCRAPE_POST_DETAIL_SCRIPT in get-post.ts also requires the item
    // to render with offsetHeight >= 100 (skips skeletons/hidden items
    // with zero or near-zero layout box).  Probe both the unfiltered
    // count (catch "menu-button selector still works but item is
    // hidden") and the scraper-equivalent count (catch "scraper would
    // skip every visible candidate") so Phase 2 can distinguish those.
    const viableItems = itemsWithMenu.filter(function (item) {
      return item.offsetHeight >= 100;
    });
    return {
      href: location.href,
      title: document.title,
      hasMain: document.querySelector('main') !== null,
      hasMainFeed: mainFeed !== null,
      mainFeedListItemCount: listItems.length,
      mainFeedListItemsWithMenuButton: itemsWithMenu.length,
      mainFeedListItemsViableForPostScrape: viableItems.length,
      hasAuthorLink: document.querySelector(${jsString(POST_AUTHOR_LINK_DOCUMENT_WIDE_SELECTOR)}) !== null,
      hasAuthorLinkInMain: document.querySelector(${jsString(POST_READY_AUTHOR_LINK_SELECTOR)}) !== null,
      hasLtrSpans: document.querySelectorAll(${jsString(POST_LTR_SPAN_FALLBACK_SELECTOR)}).length > 0,
      hasArticles: document.querySelectorAll('article').length > 0,
      hasReactLikeButton: document.querySelector(${jsString(POST_REACT_LIKE_SELECTOR)}) !== null,
      hasCommentOnButton: document.querySelector(${jsString(POST_COMMENT_ON_SELECTOR)}) !== null,
      hasTopLevelEditor: document.querySelector(${jsString(POST_EDITOR_SELECTOR)}) !== null,
      hasReactionsMenu: document.querySelector(${jsString(POST_REACTIONS_MENU_SELECTOR)}) !== null,
      commentElementCount: document.querySelectorAll(${jsString(POST_COMMENT_ELEMENT_SELECTOR)}).length,
      bodyTextSnippet: (document.body ? document.body.innerText : "").slice(0, 800),
      // NESTED under one key and placed LAST, so it sits next to
      // \`variantDetection\` in the written bundle and reads with it.  Nested
      // rather than spread: the fixed fields above are hand-written and the
      // readings below are generated from a registry that can grow, so a
      // spread would make a future adapter's key silently able to overwrite
      // one of them.  Under one key that collision cannot be constructed.
      variantAnchors: __lhPostDetailAnchorProbe(),
    };
  })()`;

async function capturePostLoadFailureInner(
  client: CDPClient,
  context: PostDetailCaptureContext,
  state: CaptureCancellationState,
): Promise<void> {
  const labels = POST_DETAIL_TRIGGER_LABELS[context.trigger];
  const timestamp = new Date().toISOString().replace(/[:.]/g, "-");
  // mkdtemp is the atomic fresh-directory primitive: it generates a
  // random suffix and creates the directory in one syscall, refusing
  // to follow any pre-existing symlink at the prefix.  This closes
  // the TOCTOU window that mkdir(recursive: true) leaves open — the
  // shared `lhremote-diagnostics` parent could otherwise be a
  // pre-existing symlink another local user controls, and recursive
  // mkdir would silently create our randomized child INSIDE the
  // attacker's target before any validation runs.  Using mkdtemp
  // directly under `os.tmpdir()` (no shared parent) means the only
  // directory in our path is the one we just created.
  const baseDir = await mkdtemp(join(tmpdir(), "lhremote-diagnostics-"));
  if (state.timedOut) return;
  // mkdtemp returns a fresh directory but mode is process-umask-
  // dependent on POSIX (typically 0o700 in Node 24+, but defensively
  // tightening here protects against umask drift).  ensureSecure-
  // DiagnosticDir also re-checks for symlink/non-directory shapes and
  // refuses if anything looks off.
  if (!(await ensureSecureDiagnosticDir(baseDir))) return;
  if (state.timedOut) return;
  const prefix = join(baseDir, `${labels.stem}-${timestamp}`);

  const info = await client.evaluate<PostDetailCaptureProbe>(
    POST_DETAIL_CAPTURE_PROBE_SCRIPT,
  );
  if (state.timedOut) return;

  // The bundle carries the trigger and the per-registered-adapter detect
  // counts alongside the DOM probes (#835).  `variantDetection` is the whole
  // diagnosis for the next dialect flip, and it is the one thing the probe
  // set above structurally cannot say: every probe there is a fixed selector,
  // so a page serving a dialect nobody has registered looks identical to one
  // whose registered adapter matched but whose field selectors went stale.
  //
  // Both halves are recorded because the diagnosis needs both: `matched`
  // picks between the three cases (none / two-or-more / exactly one) and
  // `probes` says by how much.  A bundle reading `{ sdui: 1, legacy: 1 }` is
  // a hybrid page wanting tighter detect anchors, NOT a stale field selector
  // — collapsing this to "zero versus non-zero" loses that case.
  //
  // `null` records that the detect probe yielded no usable reading — which is
  // NOT the claim "no adapter matched".  A reader must not treat it as
  // evidence about the page.
  const bundle = {
    trigger: context.trigger,
    ...info,
    variantDetection: context.detection
      ? {
          matched: context.detection.matched,
          probes: context.detection.probes,
        }
      : null,
  };

  // 0o600: owner-only rw.  POSIX-only; no-op on Windows.
  await writeFile(`${prefix}.json`, JSON.stringify(bundle, null, 2), {
    encoding: "utf8",
    mode: 0o600,
  });
  if (state.timedOut) {
    // Cap fired after JSON landed but before screenshot.  Surface the
    // path NOW — the per-invocation mkdtemp directory is the only
    // place these artifacts live, so an early return without a warn
    // would leave operators unable to find them.
    console.warn(
      `[${labels.tag}] ${labels.summary} partial: ${prefix}.json (screenshot skipped — capture cap reached)`,
    );
    return;
  }

  let wroteScreenshot = false;
  try {
    const screenshot = (await client.send("Page.captureScreenshot", {
      format: "png",
      captureBeyondViewport: true,
    })) as { data?: string };
    if (!state.timedOut && screenshot.data) {
      await writeFile(`${prefix}.png`, Buffer.from(screenshot.data, "base64"), {
        mode: 0o600,
      });
      wroteScreenshot = true;
    }
  } catch {
    // Screenshot is best-effort; info.json is the primary artifact.
  }

  // Unconditional warn — even if `state.timedOut` flipped during the
  // screenshot, we still have at least the JSON at the randomized
  // path, and the operator needs the path to find anything at all.
  // Mention `.png` only when actually written.
  const artifacts = wroteScreenshot ? "{json,png}" : "json";
  console.warn(
    `[${labels.tag}] ${labels.summary} written: ${prefix}.${artifacts}`,
  );
}

/**
 * Validate the freshly-created diagnostic directory before writing
 * personal data into it.  Callers create the directory atomically via
 * `mkdtemp` so the path itself cannot be a symlink another user pre-
 * planted, but on POSIX `mkdtemp` honors the process umask — a loose
 * umask would produce a group/world-readable directory, so this
 * function `chmod`s back to `0o700` when needed.  Also defensively
 * re-`lstat`s and refuses on the (vanishingly rare) shapes where the
 * just-created path is a symlink or not a directory.
 *
 * Returns `true` when the directory is safe to write into, `false`
 * otherwise (caller short-circuits the capture).  POSIX-only concerns;
 * on Windows the mode bits and symlink semantics differ but this
 * check is still a no-op-or-pass.
 *
 * Exported for use by `wait-for-post-load`'s own diagnostic capture
 * AND `operations/navigate-to-profile.ts`'s navigation diagnostics —
 * both paths use the same `${tmpdir()}/lhremote-diagnostics-XXXXXX/`
 * mkdtemp pattern and the same threat model, so the validation
 * primitive is centralized here.
 */
export async function ensureSecureDiagnosticDir(
  baseDir: string,
): Promise<boolean> {
  let stats: Awaited<ReturnType<typeof lstat>>;
  try {
    stats = await lstat(baseDir);
  } catch {
    return false;
  }
  if (stats.isSymbolicLink() || !stats.isDirectory()) {
    return false;
  }
  // Need to enforce the FULL `0o700` mode, not just strip group/world
  // bits.  Under a restrictive umask, mkdtemp can produce a directory
  // missing one of the owner's rwx bits (e.g. `0o600`), which would
  // pass an "any group/world bits" check while still failing the
  // subsequent writeFile because the owner lacks `x` (traverse) on
  // their own diagnostic dir.
  if ((stats.mode & 0o777) !== 0o700) {
    try {
      await chmod(baseDir, 0o700);
    } catch {
      // Could not tighten — refuse rather than write into a directory
      // that isn't reliably owner-rwx.
      return false;
    }
  }
  return true;
}
