// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (C) 2026 Oleksii PELYKH

// Types (profile, messaging, instance, account, campaign — CDP types are internal)
export type {
  Account,
  ActionBudget,
  ActionBudgetEntry,
  ActionConfig,
  ActionErrorSummary,
  ActionPeopleCounts,
  ActionStatistics,
  CampaignActionConfig,
  CampaignActionResult,
  CampaignActionUpdateConfig,
  ActionSettings,
  ActionTargetPerson,
  Campaign,
  CampaignAction,
  CampaignConfig,
  CampaignPersonEntry,
  CampaignPersonState,
  CampaignRunResult,
  CampaignState,
  EphemeralActionResult,
  EphemeralExecuteOptions,
  ResultProfileData,
  CampaignStatistics,
  CampaignStatus,
  CampaignSummary,
  CampaignUpdateConfig,
  CriticalErrorIssueData,
  DialogIssueData,
  ExcludeListEntry,
  Chat,
  ChatParticipant,
  ConversationMessages,
  ConversationThread,
  CurrentPosition,
  Education,
  ExternalId,
  ExternalIdTypeGroup,
  FeedPost,
  GetResultsOptions,
  GetStatisticsOptions,
  ImportPeopleResult,
  LimitType,
  RemovePeopleResult,
  InstanceInfo,
  InstanceIssue,
  InstancePopup,
  InstanceStatus,
  ListCampaignPeopleOptions,
  ListCampaignsOptions,
  Message,
  MessageStats,
  MessageSummary,
  MiniProfile,
  PopupState,
  PostComment,
  PostDetail,
  PostEngager,
  PostStats,
  Position,
  Profile,
  ProfileFindOptions,
  ProfileSearchOptions,
  ProfileSearchResult,
  ProfileSummary,
  ReactionCount,
  RunnerState,
  Skill,
  BasicSearchParams,
  BooleanExpressionInput,
  BooleanExpressionRaw,
  BooleanExpressionStructured,
  CompanySizeEntry,
  ConnectionDegreeEntry,
  EntityMatch,
  EntityType,
  FunctionEntry,
  IndustryEntry,
  ProfileLanguageEntry,
  ReferenceDataType,
  SNFilter,
  SNFilterValue,
  SNSearchParams,
  SeniorityEntry,
  SourceTier,
  SourceType,
  StartInstanceParams,
  StartInstanceResult,
  ThrottleStatus,
  UIHealthStatus,
  UrlBuilderResult,
} from "./types/index.js";

// Services
export {
  AccountResolutionError,
  ActionExecutionError,
  type ActionResult,
  AppLaunchError,
  AppNotFoundError,
  AppService,
  type AppServiceOptions,
  BudgetExceededError,
  CampaignExecutionError,
  CampaignService,
  CampaignTimeoutError,
  EphemeralCampaignService,
  CollectionBusyError,
  CollectionError,
  type DatabaseContext,
  buildBasicSearchUrl,
  buildBooleanExpression,
  buildParameterisedUrl,
  buildSNSearchUrl,
  detectSourceType,
  getFixedUrl,
  getParameterType,
  isFixedUrlType,
  isParameterisedType,
  isSNSearchBuilderType,
  isSearchBuilderType,
  ExtractionTimeoutError,
  type InstanceDatabaseContext,
  InstanceNotRunningError,
  InstanceService,
  InvalidProfileUrlError,
  LauncherService,
  LinkedHelperNotRunningError,
  LinkedHelperUnreachableError,
  resolveAccount,
  ServiceError,
  StartInstanceError,
  startInstanceWithRecovery,
  UIBlockedError,
  validateSourceType,
  type StartInstanceOutcome,
  checkStatus,
  type AccountInstanceStatus,
  type DatabaseStatus,
  type LauncherStatus,
  type StatusReport,
  waitForInstancePort,
  waitForInstanceShutdown,
  withDatabase,
  withInstanceDatabase,
  NodeIntegrationUnavailableError,
  VoyagerInterceptor,
  type VoyagerFetchOptions,
  type VoyagerResponse,
  type VoyagerResponseHandler,
  WrongPortError,
} from "./services/index.js";

// Data access
export {
  ActionBudgetRepository,
  CampaignExcludeListRepository,
  CampaignRepository,
  CampaignStatisticsRepository,
  CollectionListRepository,
  type CollectionSummary,
  DatabaseClient,
  type DatabaseClientOptions,
  discoverAllDatabases,
  discoverDatabase,
  MessageRepository,
  ProfileRepository,
} from "./db/index.js";

// Formats
export {
  CampaignFormatError,
  FormatError,
  parseCampaignJson,
  parseCampaignYaml,
  serializeCampaignJson,
  serializeCampaignYaml,
} from "./formats/index.js";

// Data (action types catalog)
export {
  type ActionCategory,
  type ActionType,
  type ActionTypeCatalog,
  type ActionTypeInfo,
  type ConfigFieldSchema,
  getActionTypeCatalog,
  getActionTypeInfo,
  getFunctionById,
  getIndustryById,
  getLinkedInReferenceData,
  getSeniorityById,
  isReferenceDataType,
} from "./data/index.js";

// Errors (DB + CDP errors can propagate through the service layer)
export {
  ActionNotFoundError,
  CampaignNotFoundError,
  ChatNotFoundError,
  DatabaseError,
  DatabaseNotFoundError,
  ExcludeListNotFoundError,
  NoNextActionError,
  ProfileNotFoundError,
} from "./db/index.js";

export {
  CDPConnectionError,
  CDPError,
  CDPEvaluationError,
  CDPTimeoutError,
  discoverInstancePort,
  discoverTargets,
  findApp,
  resolveAppPort,
  type AppRole,
  type DiscoveredApp,
  killInstanceProcesses,
} from "./cdp/index.js";

// Operations (shared business logic for CLI + MCP)
export {
  type ConnectionOptions,
  // Campaign CRUD
  campaignGet,
  type CampaignGetInput,
  type CampaignGetOutput,
  campaignList,
  type CampaignListInput,
  type CampaignListOutput,
  campaignCreate,
  type CampaignCreateInput,
  type CampaignCreateOutput,
  campaignUpdate,
  type CampaignUpdateInput,
  type CampaignUpdateOutput,
  campaignDelete,
  type CampaignDeleteInput,
  type CampaignDeleteOutput,
  campaignErase,
  type CampaignEraseInput,
  type CampaignEraseOutput,
  // People collection
  collectPeople,
  type CollectPeopleInput,
  type CollectPeopleOutput,
  // Campaign people
  campaignListPeople,
  type CampaignListPeopleInput,
  type CampaignListPeopleOutput,
  // Campaign execution
  campaignStart,
  type CampaignStartInput,
  type CampaignStartOutput,
  campaignStop,
  type CampaignStopInput,
  type CampaignStopOutput,
  campaignRetry,
  type CampaignRetryInput,
  type CampaignRetryOutput,
  campaignMoveNext,
  type CampaignMoveNextInput,
  type CampaignMoveNextOutput,
  campaignStatistics,
  type CampaignStatisticsInput,
  type CampaignStatisticsOutput,
  campaignStatus,
  type CampaignStatusInput,
  type CampaignStatusOutput,
  // Campaign configuration
  campaignAddAction,
  type CampaignAddActionInput,
  type CampaignAddActionOutput,
  campaignRemoveAction,
  type CampaignRemoveActionInput,
  type CampaignRemoveActionOutput,
  campaignUpdateAction,
  type CampaignUpdateActionInput,
  type CampaignUpdateActionOutput,
  campaignReorderActions,
  type CampaignReorderActionsInput,
  type CampaignReorderActionsOutput,
  campaignExport,
  type CampaignExportInput,
  type CampaignExportOutput,
  // Exclude list
  campaignExcludeAdd,
  type CampaignExcludeAddInput,
  type CampaignExcludeAddOutput,
  campaignExcludeRemove,
  type CampaignExcludeRemoveInput,
  type CampaignExcludeRemoveOutput,
  campaignExcludeList,
  type CampaignExcludeListInput,
  type CampaignExcludeListOutput,
  // Post interaction
  commentOnPost,
  type CommentOnPostInput,
  type CommentOnPostOutput,
  // Feed
  getFeed,
  type GetFeedInput,
  type GetFeedOutput,
  // Post detail
  getPost,
  type GetPostInput,
  type GetPostOutput,
  // Post analytics
  getPostStats,
  extractPostUrn,
  resolvePostDetailUrl,
  type GetPostStatsInput,
  type GetPostStatsOutput,
  getPostEngagers,
  type GetPostEngagersInput,
  type GetPostEngagersOutput,
  // Post search
  searchPosts,
  type SearchPostsInput,
  type SearchPostsOutput,
  // Profile activity
  getProfileActivity,
  extractProfileId,
  type GetProfileActivityInput,
  type GetProfileActivityOutput,
  // Action budget & throttle status
  getActionBudget,
  type GetActionBudgetInput,
  type GetActionBudgetOutput,
  getThrottleStatus,
  type GetThrottleStatusInput,
  type GetThrottleStatusOutput,
  // Error detection
  getErrors,
  type GetErrorsInput,
  type GetErrorsOutput,
  dismissErrors,
  type DismissErrorsInput,
  type DismissErrorsOutput,
  // Messaging
  queryMessages,
  type QueryMessagesInput,
  type QueryMessagesOutput,
  checkReplies,
  type CheckRepliesInput,
  type CheckRepliesOutput,
  scrapeMessagingHistory,
  type ScrapeMessagingHistoryInput,
  type ScrapeMessagingHistoryOutput,
  importPeopleFromUrls,
  type ImportPeopleFromUrlsInput,
  type ImportPeopleFromUrlsOutput,
  campaignRemovePeople,
  type CampaignRemovePeopleInput,
  type CampaignRemovePeopleOutput,
  // Collections (Lists)
  listCollections,
  type ListCollectionsInput,
  type ListCollectionsOutput,
  createCollection,
  type CreateCollectionInput,
  type CreateCollectionOutput,
  deleteCollection,
  type DeleteCollectionInput,
  type DeleteCollectionOutput,
  addPeopleToCollection,
  type AddPeopleToCollectionInput,
  type AddPeopleToCollectionOutput,
  removePeopleFromCollection,
  type RemovePeopleFromCollectionInput,
  type RemovePeopleFromCollectionOutput,
  importPeopleFromCollection,
  type ImportPeopleFromCollectionInput,
  type ImportPeopleFromCollectionOutput,
  // Standalone actions
  visitProfile,
  type VisitProfileInput,
  type VisitProfileOutput,
  // Post interaction
  reactToPost,
  REACTION_TYPES,
  type ReactToPostInput,
  type ReactToPostOutput,
  type ReactionType,
  // Individual actions (ephemeral campaign)
  type EphemeralActionInput,
  messagePerson,
  type MessagePersonInput,
  type MessagePersonOutput,
  sendInvite,
  type SendInviteInput,
  type SendInviteOutput,
  sendInmail,
  type SendInmailInput,
  type SendInmailOutput,
  followPerson,
  type FollowPersonInput,
  type FollowPersonOutput,
  endorseSkills,
  type EndorseSkillsInput,
  type EndorseSkillsOutput,
  likePersonPosts,
  type LikePersonPostsInput,
  type LikePersonPostsOutput,
  removeConnection,
  type RemoveConnectionInput,
  type RemoveConnectionOutput,
  enrichProfile,
  type EnrichProfileInput,
  type EnrichProfileOutput,
  type EnrichmentCategory,
  // URL building & entity resolution
  buildLinkedInUrl,
  type BuildLinkedInUrlInput,
  type BuildLinkedInUrlOutput,
  resolveLinkedInEntity,
  type ResolveLinkedInEntityInput,
  type ResolveLinkedInEntityOutput,
} from "./operations/index.js";

// LinkedIn DOM automation & selectors
export {
  click,
  getElementCenter,
  hover,
  humanizedClick,
  humanizedHover,
  humanizedScrollY,
  HumanizedMouse,
  scrollTo,
  typeText,
  type TypeMethod,
  waitForElement,
  type WaitForElementOptions,
  COMMENT_INPUT,
  COMMENT_SUBMIT_BUTTON,
  FEED_POST_CONTAINER,
  PAGINATION_TRIGGER,
  POST_AUTHOR_INFO,
  POST_AUTHOR_NAME,
  POST_TEXT_CONTENT,
  REACTION_CELEBRATE,
  REACTION_FUNNY,
  REACTION_INSIGHTFUL,
  REACTION_LIKE,
  REACTION_LOVE,
  REACTION_SUPPORT,
  REACTION_TRIGGER,
  REACTIONS_MENU,
  SCROLL_CONTAINER,
  SELECTORS,
  type SelectorName,
} from "./linkedin/index.js";

// Constants
export { DEFAULT_CDP_PORT } from "./constants.js";

// Utilities
export { delay, randomDelay, errorMessage, isCdpPort, isLoopbackAddress } from "./utils/index.js";
